{{- if and .Values.secret.username .Values.secret.password -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "servercow-webhook.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "servercow-webhook.name" . }}
    chart: {{ include "servercow-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  username: {{ .Values.secret.username | b64enc | quote }}
  password: {{ .Values.secret.password | b64enc | quote }}
{{ end }}